# Generated by Django 5.2.17 on 2026-10-01 15:21

import contas.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "cnpj",
                    models.CharField(
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                        validators=[contas.validators.validar_cnpj],
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=120, verbose_name="razão social"),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=120, verbose_name="e-mail")),
            ],
            options={
                "db_table": "empresa",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=120,
                        primary_key=True,
                        serialize=False,
                        verbose_name="e-mail",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "password",
                    models.CharField(
                        db_column="senha", max_length=255, verbose_name="senha"
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[("GESTOR", "Gestor"), ("OPERADOR", "Operador")],
                        default="OPERADOR",
                        max_length=20,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="cnpj_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admins",
                        to="contas.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "admin",
                "ordering": ["nome"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("perfil__in", ["GESTOR", "OPERADOR"])),
                        name="ck_admin_perfil",
                    )
                ],
            },
        ),
    ]
