# Generated by Django 5.2.17 on 2026-10-01 15:21

import contas.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        validators=[contas.validators.validar_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("telefone", models.CharField(max_length=15)),
                (
                    "num_cnh",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="nº da CNH"
                    ),
                ),
                ("validade_cnh", models.DateField(verbose_name="validade da CNH")),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="cnpj_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motoristas",
                        to="contas.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "motorista",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PlanoManutencao",
            fields=[
                ("id_plano", models.AutoField(primary_key=True, serialize=False)),
                (
                    "descricao",
                    models.CharField(max_length=120, verbose_name="descrição"),
                ),
                (
                    "tipo_veiculo",
                    models.CharField(
                        choices=[
                            ("CARRO", "Carro"),
                            ("MOTO", "Moto"),
                            ("UTILITARIO", "Utilitário"),
                            ("VAN", "Van"),
                            ("CAMINHAO", "Caminhão"),
                            ("ONIBUS", "Ônibus"),
                        ],
                        max_length=30,
                        verbose_name="tipo de veículo",
                    ),
                ),
                (
                    "intervalo_km",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="intervalo (km)"
                    ),
                ),
                (
                    "intervalo_meses",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="intervalo (meses)"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="cnpj_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos",
                        to="contas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "plano de manutenção",
                "db_table": "plano_manutencao",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "placa",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[contas.validators.validar_placa],
                    ),
                ),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=60)),
                ("ano", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CARRO", "Carro"),
                            ("MOTO", "Moto"),
                            ("UTILITARIO", "Utilitário"),
                            ("VAN", "Van"),
                            ("CAMINHAO", "Caminhão"),
                            ("ONIBUS", "Ônibus"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("MANUTENCAO", "Em manutenção"),
                            ("INATIVO", "Inativo"),
                        ],
                        default="ATIVO",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="cnpj_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="contas.empresa",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        blank=True,
                        db_column="cpf_motorista",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos",
                        to="frota.motorista",
                    ),
                ),
            ],
            options={
                "db_table": "veiculo",
                "ordering": ["placa"],
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "numero",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="número"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="descrição"),
                ),
                ("data_abertura", models.DateField(verbose_name="data de abertura")),
                (
                    "data_conclusao",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de conclusão"
                    ),
                ),
                ("quilometragem", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("APROVADA", "Aprovada"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("CONCLUIDA", "Concluída"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ABERTA",
                        max_length=20,
                    ),
                ),
                ("oficina", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "aprovador",
                    models.ForeignKey(
                        blank=True,
                        db_column="email_aprovador",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emitente",
                    models.ForeignKey(
                        db_column="email_emitente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_emitidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_plano",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="frota.planomanutencao",
                        verbose_name="plano de manutenção",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        db_column="placa_veiculo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="frota.veiculo",
                        verbose_name="veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "ordem de serviço",
                "verbose_name_plural": "ordens de serviço",
                "db_table": "ordem_servico",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="LeituraOdometro",
            fields=[
                ("codigo", models.AutoField(primary_key=True, serialize=False)),
                ("data_leitura", models.DateField(verbose_name="data da leitura")),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("MOTORISTA", "Motorista"),
                            ("ORDEM_SERVICO", "Ordem de serviço"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("quilometragem", models.IntegerField()),
                (
                    "veiculo",
                    models.ForeignKey(
                        db_column="placa_veiculo",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leituras",
                        to="frota.veiculo",
                        verbose_name="veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "leitura de odômetro",
                "db_table": "leitura_odometro",
                "ordering": ["-data_leitura", "-quilometragem"],
            },
        ),
        migrations.AddConstraint(
            model_name="planomanutencao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("intervalo_km__isnull", False),
                    ("intervalo_meses__isnull", False),
                    _connector="OR",
                ),
                name="ck_plano_algum_intervalo",
            ),
        ),
        migrations.AddConstraint(
            model_name="planomanutencao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("intervalo_km__isnull", True),
                    ("intervalo_km__gt", 0),
                    _connector="OR",
                ),
                name="ck_plano_intervalo_km",
            ),
        ),
        migrations.AddConstraint(
            model_name="planomanutencao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("intervalo_meses__isnull", True),
                    ("intervalo_meses__gt", 0),
                    _connector="OR",
                ),
                name="ck_plano_intervalo_meses",
            ),
        ),
        migrations.AddConstraint(
            model_name="veiculo",
            constraint=models.CheckConstraint(
                condition=models.Q(("ano__gte", 1950), ("ano__lte", 2100)),
                name="ck_veiculo_ano",
            ),
        ),
        migrations.AddConstraint(
            model_name="veiculo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("situacao__in", ["ATIVO", "MANUTENCAO", "INATIVO"])
                ),
                name="ck_veiculo_situacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["ABERTA", "APROVADA", "EM_EXECUCAO", "CONCLUIDA", "CANCELADA"],
                    )
                ),
                name="ck_os_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valor__isnull", True), ("valor__gte", 0), _connector="OR"
                ),
                name="ck_os_valor",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quilometragem__isnull", True),
                    ("quilometragem__gte", 0),
                    _connector="OR",
                ),
                name="ck_os_quilometragem",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordemservico",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("data_conclusao__isnull", True),
                    ("data_conclusao__gte", models.F("data_abertura")),
                    _connector="OR",
                ),
                name="ck_os_datas",
            ),
        ),
        migrations.AddConstraint(
            model_name="leituraodometro",
            constraint=models.CheckConstraint(
                condition=models.Q(("quilometragem__gte", 0)), name="ck_leitura_km"
            ),
        ),
    ]
