# Generated by Django 5.2.17 on 2026-10-01 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frota", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="veiculo",
            options={"ordering": ["placa"], "verbose_name": "veículo"},
        ),
        migrations.AlterField(
            model_name="leituraodometro",
            name="quilometragem",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="quilometragem",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="planomanutencao",
            name="intervalo_km",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="intervalo (km)",
            ),
        ),
        migrations.AlterField(
            model_name="planomanutencao",
            name="intervalo_meses",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="intervalo (meses)",
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1950),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
    ]
