-- =====================================================================
-- CarHealth - Modelo físico (PostgreSQL 16)
-- Equivalente ao que as migrações do Django criam (python manage.py migrate).
-- Use este script apenas para documentação ou para criar o banco sem o Django.
-- =====================================================================

CREATE TABLE empresa (
    cnpj          varchar(14)  NOT NULL,
    razao_social  varchar(120) NOT NULL,
    telefone      varchar(15)  NOT NULL,
    email         varchar(120) NOT NULL,
    CONSTRAINT empresa_pkey PRIMARY KEY (cnpj)
);

CREATE TABLE motorista (
    cpf           varchar(11)  NOT NULL,
    nome          varchar(120) NOT NULL,
    telefone      varchar(15)  NOT NULL,
    num_cnh       varchar(11)  NOT NULL,
    validade_cnh  date         NOT NULL,
    cnpj_empresa  varchar(14)  NOT NULL,
    CONSTRAINT motorista_pkey PRIMARY KEY (cpf),
    CONSTRAINT uq_motorista_cnh UNIQUE (num_cnh)
);

CREATE TABLE veiculo (
    placa          varchar(8)  NOT NULL,
    marca          varchar(50) NOT NULL,
    modelo         varchar(60) NOT NULL,
    ano            integer     NOT NULL,
    tipo           varchar(30) NOT NULL,
    situacao       varchar(20) NOT NULL,
    cnpj_empresa   varchar(14) NOT NULL,
    cpf_motorista  varchar(11),
    CONSTRAINT veiculo_pkey PRIMARY KEY (placa),
    CONSTRAINT ck_veiculo_ano CHECK (ano BETWEEN 1950 AND 2100),
    CONSTRAINT ck_veiculo_situacao CHECK (situacao IN ('ATIVO', 'MANUTENCAO', 'INATIVO'))
);

CREATE TABLE admin (
    email         varchar(120) NOT NULL,
    nome          varchar(120) NOT NULL,
    senha         varchar(255) NOT NULL,   -- hash PBKDF2-SHA256, nunca texto puro
    perfil        varchar(20)  NOT NULL,
    cnpj_empresa  varchar(14)  NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (email),
    CONSTRAINT ck_admin_perfil CHECK (perfil IN ('GESTOR', 'OPERADOR'))
);

CREATE TABLE plano_manutencao (
    id_plano         integer GENERATED BY DEFAULT AS IDENTITY,
    descricao        varchar(120) NOT NULL,
    tipo_veiculo     varchar(30)  NOT NULL,
    intervalo_km     integer,
    intervalo_meses  integer,
    cnpj_empresa     varchar(14)  NOT NULL,
    CONSTRAINT plano_manutencao_pkey PRIMARY KEY (id_plano),
    CONSTRAINT ck_plano_algum_intervalo CHECK (intervalo_km IS NOT NULL OR intervalo_meses IS NOT NULL),
    CONSTRAINT ck_plano_intervalo_km CHECK (intervalo_km IS NULL OR intervalo_km > 0),
    CONSTRAINT ck_plano_intervalo_meses CHECK (intervalo_meses IS NULL OR intervalo_meses > 0)
);

CREATE TABLE leitura_odometro (
    codigo         integer GENERATED BY DEFAULT AS IDENTITY,
    data_leitura   date        NOT NULL,
    origem         varchar(20) NOT NULL,
    placa_veiculo  varchar(8)  NOT NULL,
    quilometragem  integer     NOT NULL,
    CONSTRAINT leitura_odometro_pkey PRIMARY KEY (codigo),
    CONSTRAINT ck_leitura_km CHECK (quilometragem >= 0)
);

CREATE TABLE ordem_servico (
    numero           integer GENERATED BY DEFAULT AS IDENTITY,
    descricao        varchar(255)  NOT NULL,
    data_abertura    date          NOT NULL,
    data_conclusao   date,
    quilometragem    integer,
    status           varchar(20)   NOT NULL,
    oficina          varchar(120),
    valor            numeric(10,2),
    placa_veiculo    varchar(8)    NOT NULL,
    id_plano         integer,
    email_emitente   varchar(120)  NOT NULL,
    email_aprovador  varchar(120),
    CONSTRAINT ordem_servico_pkey PRIMARY KEY (numero),
    CONSTRAINT ck_os_status CHECK (status IN ('ABERTA', 'APROVADA', 'EM_EXECUCAO', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT ck_os_valor CHECK (valor IS NULL OR valor >= 0),
    CONSTRAINT ck_os_quilometragem CHECK (quilometragem IS NULL OR quilometragem >= 0),
    CONSTRAINT ck_os_datas CHECK (data_conclusao IS NULL OR data_conclusao >= data_abertura)
);

-- Chaves estrangeiras
ALTER TABLE motorista        ADD CONSTRAINT fk_motorista_empresa FOREIGN KEY (cnpj_empresa)    REFERENCES empresa (cnpj);
ALTER TABLE veiculo          ADD CONSTRAINT fk_veiculo_empresa   FOREIGN KEY (cnpj_empresa)    REFERENCES empresa (cnpj);
ALTER TABLE veiculo          ADD CONSTRAINT fk_veiculo_motorista FOREIGN KEY (cpf_motorista)   REFERENCES motorista (cpf);
ALTER TABLE admin            ADD CONSTRAINT fk_admin_empresa     FOREIGN KEY (cnpj_empresa)    REFERENCES empresa (cnpj);
ALTER TABLE plano_manutencao ADD CONSTRAINT fk_plano_empresa     FOREIGN KEY (cnpj_empresa)    REFERENCES empresa (cnpj);
ALTER TABLE leitura_odometro ADD CONSTRAINT fk_leitura_veiculo   FOREIGN KEY (placa_veiculo)   REFERENCES veiculo (placa);
ALTER TABLE ordem_servico    ADD CONSTRAINT fk_os_veiculo        FOREIGN KEY (placa_veiculo)   REFERENCES veiculo (placa);
ALTER TABLE ordem_servico    ADD CONSTRAINT fk_os_plano          FOREIGN KEY (id_plano)        REFERENCES plano_manutencao (id_plano);
ALTER TABLE ordem_servico    ADD CONSTRAINT fk_os_emitente       FOREIGN KEY (email_emitente)  REFERENCES admin (email);
ALTER TABLE ordem_servico    ADD CONSTRAINT fk_os_aprovador      FOREIGN KEY (email_aprovador) REFERENCES admin (email);

-- Índices nas chaves estrangeiras (aceleram filtros por empresa/veículo)
CREATE INDEX ix_motorista_empresa  ON motorista (cnpj_empresa);
CREATE INDEX ix_veiculo_empresa    ON veiculo (cnpj_empresa);
CREATE INDEX ix_veiculo_motorista  ON veiculo (cpf_motorista);
CREATE INDEX ix_admin_empresa      ON admin (cnpj_empresa);
CREATE INDEX ix_plano_empresa      ON plano_manutencao (cnpj_empresa);
CREATE INDEX ix_leitura_veiculo    ON leitura_odometro (placa_veiculo);
CREATE INDEX ix_os_veiculo         ON ordem_servico (placa_veiculo);
CREATE INDEX ix_os_plano           ON ordem_servico (id_plano);
CREATE INDEX ix_os_emitente        ON ordem_servico (email_emitente);
CREATE INDEX ix_os_aprovador       ON ordem_servico (email_aprovador);
